export default {
    en: {
        ui: {
            footer_description: 'Open Source Project developed by',
            data_explorer: 'Data Explorer',
            vault: 'Vault',
            logout: 'Logout'
        },
        general: {
            unlock_wallet: "UNLOCK WALLET",
            send: 'Send',
            receive: 'Receive',
            password_incorrect: "Password is incorrect!",
            idanode_problem: "Seems there's a problem, please retry or change node!",
            decrypt_wallet_first: "Decrypt your wallet first",
            date: "Date",
            recipient: "Recipient",
            value: "Value",
            txid: 'TxID',
            block: 'Block'
        },
        home: {
            balance: 'Your balance',
            open_block_explorer: 'Open block explorer',
            your_address: 'Your address',
            copy_address: 'Copy address to clipboard',
            import_wallet: 'Import a wallet',
            drag_drop: 'Just drag and drop here or select a .sid file',
            drop: 'Drop file here...',
            send_lyra: 'Send LYRA',
            main_description: "Scrypta Manent is an application that you can use as a Wallet in Cloud, which will allow you to send and receive LYRA. You can also use it to upload files directly into the blockchain and encrypt them, thanks to IPFS technology and IdANodes. You have to make a backup. Please remind, you are ONLY responsible for this .sid file and password associated. No one will have to copy or to rescue it, so keep it safe.",
            create_wallet: 'Create a new wallet',
            enter_password: "Enter a strong wallet password and don't forget it!",
            repeat_password: "Repeat again your password.",
            create_button: "CREATE NOW",
            import_existing_wallet: "Import an existing wallet",
            select_sid: "Select a valid .SID file generated by Manent App or ScryptaID or use directly ScryptaID to inject the wallet.",
            import_button: "IMPORT NOW",
            choose_backup_method: "Please choose a method:",
            store_sid: "Store the .sid file in your device",
            print_paper_wallet: "Print paper wallet",
            sync_mobile: "Sync to mobile app",
            unlock_wallet_first: "Unlock your wallet first",
            enter_wallet_password: "Enter wallet password",
            sync_app_description: 'Open Manent app and click "Restore paper wallet", then scan this QR code.',
            sync_app_title: 'Sync mobile app',
            backup_or_sync: 'Backup or Sync',
            no_transactions: 'No transactions.',
            paper_wallet_description: "This is your paper wallet. Print it and don't share this informations.",
            address_copied: 'Address was copied',
            address_copy_error: 'Oops, unable to copy',
            loading_transactions: "Loading transactions..."
        },
    },
    it: {
        home: {
            
        },
    },
};